version: '2'
services:
  registry:
    restart: always
    container_name: registry
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - ./data:/var/lib/registry
      - ./config:/etc/docker/registry

